#ifndef VIO_ERROR_H
#define VIO_ERROR_H

#include <stdint.h>

typedef enum {
    VE_ALLOC_FAIL = 1,

    VE_TOKENIZER_INVALID_STATE,
    VE_TOKENIZER_BAD_ESCAPE_SEQUENCE,
    VE_TOKENIZER_BAD_NUMBER,
    VE_TOKENIZER_UNTERMINATED_STRING_LITERAL,
    VE_TOKENIZER_UNTERMINATED_RULE_NAME,
    VE_TOKENIZER_BAD_RULE_NAME,
    VE_TOKENIZER_UNTERMINATED_MATCH_STRING,
    VE_TOKENIZER_UNEXPECTED_EOF,

    VE_STACK_EMPTY,
    VE_STACK_OVERFLOW,

    VE_STRICT_TYPE_FAIL,
    VE_WRONG_TYPE,
    VE_NUMERIC_CONVERSION_FAIL,

    VE_DICTIONARY_ALLOC_FAIL,

    VE_EXCEEDED_MAX_CALL_DEPTH,
    VE_BAD_OPCODE
} vio_err_t;

#endif
