#include <stdint.h>

typedef enum {
    VE_ALLOC_FAIL				=  1,

    VE_TOKENIZER_INVALID_STATE			=  2,
    VE_TOKENIZER_BAD_ESCAPE_SEQUENCE		=  3,
    VE_TOKENIZER_BAD_NUMBER			=  4,
    VE_TOKENIZER_UNTERMINATED_STRING_LITERAL	=  5,
    VE_TOKENIZER_UNTERMINATED_RULE_NAME		=  6,
    VE_TOKENIZER_BAD_RULE_NAME			=  7,
    VE_TOKENIZER_UNTERMINATED_MATCH_STRING	=  8,
    VE_TOKENIZER_UNEXPECTED_EOF			=  9,

    VE_STACK_EMPTY				= 10,
    VE_STACK_OVERFLOW				= 11,

    VE_STRICT_TYPE_FAIL				= 12,
    VE_WRONG_TYPE				= 13
} vio_err_t;
